name: gamification
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  adaptive_scrollbar: ^2.1.2
  analyzer: any
  animated_size_and_fade: ^3.0.1
  audioplayers: ^5.0.0
  better_player: ^0.0.83
  chewie: 1.5.0
  cross_scroll: ^0.0.75
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  easy_localization: ^3.0.1
  easy_sidemenu: ^0.3.1
  fluid_bottom_nav_bar: ^1.4.0
  flutter:
    sdk: flutter
  flutter_phoenix: ^1.1.0
  flutter_rating_bar: ^4.0.1
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.2.1
  freezed: ^2.0.3+1
  get_it: ^7.2.0
  im_stepper: ^1.0.1+1
  image_picker: ^0.8.6+4
  internet_connection_checker: ^0.0.1+3
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  lottie: ^1.2.0
  material_design_icons_flutter: ^5.0.6595
  mime: ^1.0.4
  number_paginator: ^0.2.3

  persistent_bottom_nav_bar: ^5.0.2
  photo_view: ^0.14.0
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.1.1
  responsive_framework: ^0.2.0
  responsive_sizer: ^3.1.1
  retrofit: ^3.0.1+1
  rive: ^0.11.6
  rxdart: ^0.27.4
  scrollable_positioned_list: ^0.3.5
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.0.1
  stacked_card_carousel: ^0.0.4
  step_progress_indicator: ^1.0.2
  sticky_headers: ^0.3.0+2
  transitioned_indexed_stack: ^1.0.2
  video_player: ^2.6.1
  cached_network_image: ^3.2.3
  percent_indicator: ^4.2.3
  webview_flutter: ^4.2.2
  bubble: ^1.2.1
  group_button: ^5.2.2
  chat_bubbles: any
  xml: ^6.0.1
  path_provider: ^2.0.0
  duration: ^3.0.13
  screenshot: ^2.1.0
  image_gallery_saver: ^2.0.3
  permission_handler: ^10.4.3
  share_plus: any
  animated_button: ^0.2.0

dev_dependencies:
  build_runner: ^2.1.10
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  # native splash
  flutter_native_splash: ^2.2.15
  flutter_test:
    sdk: flutter

  # create auto generator files in project
  retrofit_generator: ^4.2.0
  timer_count_down: ^2.2.2
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/edu_gamer_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/json/
    - assets/rive/
    - assets/translations/ar-EGY.json
    - assets/translations/en-US.json

  fonts:
    - family: Segoe
      fonts:
        - asset: assets/fonts/Segoe-Regular.ttf
          weight: 400
        - asset: assets/fonts/Segoe-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Bold.ttf
          weight: 700
        - asset: assets/fonts/Oxygen-Regular.ttf
          weight: 400
        - asset: assets/fonts/Oxygen-Light.ttf
          weight: 300
    - family: MPLUSRounded1c
      fonts:
        - asset: assets/fonts/MPLUSRounded1c-Medium.ttf
          weight: 500
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Medium.ttf
          weight: 500

    - family: DINNext
      fonts:
        - asset: assets/fonts/DIN-Next-Rounded-LT-W01-Regular.ttf
          weight: 400
        - asset: assets/fonts/DIN-Next-Rounded-LT-W04-Medium.ttf
          weight: 500

    - family: feather
      fonts:
        - asset: assets/fonts/feather-ttf.ttf
          weight: 400

flutter_native_splash:
  image: assets/images/edu_gamer_logo.png
  color: "#22252d" #dark
  image_dark: assets/images/edu_gamer_logo.png
  color_dark: "#22252d"
  android: true
  ios: truef
  android_12:
    image: assets/images/edu_gamer_logo.png
    icon_background_color: "#22252d"
    image_dark: assets/images/edu_gamer_logo.png
    icon_background_color_dark: "#22252d"
